import React, {FC} from 'react';
import "./ChoosePerfume.css";



const ChoosePerfume: FC = () => {
    return (
        <div className="container mt-5">
            <h4>QUEL PARFUM CHOISIR EN FONCTION DE L'ÂGE D'UNE FEMME ?</h4> <br/>
            <img src="https://www.tendance-parfums.com/media/wysiwyg/quel-parfum-femme-choisir.jpg" className="rounded mx-auto d-block"/> <br/>
            <h5>Trouver un parfum est loin d'être une chose facile. En effet, votre choix dépend de tout un tas de paramètres différents. Même si les puristes disent qu’une fois que l'on a trouvé sa fragrance favorite il ne faut plus en changer, nous avons tendance à croire que le parfum doit évoluer avec vous. Tout d'abord, les modes évoluent d'année en année, au même titre que dans le milieu de la couture par exemple. Ensuite, il est recommandé de ne pas porter la même essence en été et en hiver. Lorsqu'il fait chaud, mieux vaut favoriser la légèreté, alors que les fraîches températures de l'hiver permettent tout à fait de porter des parfums plus opulents. Enfin, le dernier paramètre et non des moindres : votre âge. En effet, une adolescente ne portera pas la même essence qu’une dame âgée de 70 ans ! Là encore, l'idée est de révéler au mieux votre personnalité. Or, votre caractère évolue bel et bien en fonction de votre âge. Ainsi, même si votre ambition est de garder pour toujours votre âme d'enfant, nous vous recommandons tout de même de faire évoluer votre essence au fil des décennies.</h5>
            <h3 className="ml-2 mr-2">CHOISIR UN PARFUM POUR UNE JEUNE FILLE </h3>
            <img src="https://www.tendance-parfums.com/media/wysiwyg/CHOISIR-PARFUM/choisir-un-parfum-pour-une-jeune-fille.jpg" className="rounded float-left"/>
             <h5>Si pendant bien des années le parfum était réservé à une clientèle d'adultes, la tendance est aujourd'hui bien différente. En effet, de façon à initier les plus jeunes au monde des odeurs dès leur plus tendre enfance, les parfumeurs conçoivent des Eaux de Senteur. Il s'agit de parfums assez volatils, conçus sans alcool, et spécifiquement étudiés pour la peau très fragile des bébés. Ainsi, dès l'âge de trois mois, les petites filles peuvent être parfumées. C'est ainsi que commence leur éducation olfactive pour évoluer tout le restant de leur vie. Il existe ensuite des parfums pour les enfants qui deviennent un peu plus tenaces. Et ceux collant à l’âge de l'adolescence permettant goûter aux joies des vrais parfums semblables à ceux des adultes.</h5>
             <h3 className="ml-2 mr-2"> Le passage de l'enfance à l'adolescence</h3>
              <h5>Les parfums pour enfants, c'est-à-dire ceux que l'on peut porter à partir de trois ans, visent surtout à satisfaire le plaisir des enfants. En effet, les petites filles aiment généralement reproduire les gestes de leurs parents. Par conséquent, elles se parfument surtout pour faire comme leur maman. Cela leur permet néanmoins de sentir bon et d'appréhender les premières odeurs. À cet âge, comme pour les bébés dans une moindre mesure, leur peau est plus fragile. Les parfums contiennent donc peu d'alcool. Ils sont souvent assez fruités, gourmands et très girly. En d'autres termes, ils sentent bon la petite fille. C'est à partir de l'adolescence que le parfum se modifie. C'est à cet instant que les jeunes filles choisissent leur premier vrai parfum. L'idée est toutefois de préserver leur insouciance et de ne pas encore les orienter vers une fragrance qui fasse trop adulte. Pour cela, l’objectif est de trouver un juste compromis entre les senteurs enfantines et celles d'une vraie femme. Nous vous recommandons de vous orienter vers des senteurs légères et aériennes, fraîches et acidulées, un brin gourmandes. En règle générale, les jeunes filles aiment les parfums qui les plongent dans un univers bucolique et poétique. </h5>
              <h3 className="ml-2 mr-2"> La jeunesse… Là où l'on croit encore au prince charmant</h3>
              <h5>Dans le même registre, les jeunes filles aiment par-des-sus tout le romantisme. L'adolescence est encore un âge où les femmes en devenir se laissent bercer par leurs douces illusions. Elles croient encore dur comme fer que le prince charmant existe. Loin de nous l'idée de vouloir les sortir de leur torpeur, nous les incitons totalement à prolonger ce fantasme absolu par l'utilisation d'un parfum poétique. Sachez que certaines enseignes ont le don de nous transporter dans de véritables contes de fées. À titre d'exemple, Cacharel, Nina Ricci et Lolita Lempicka sont des adeptes de ce registre. Certaines de leurs fragrances s'adressent aux jeunes filles et cela se remarque dès la vision de leurs flacons ou de leurs publicités. Les coloris utilisés ne sont autres que le rose tendre, le violet ou le doré, autant de nuances qui ont une connotation fantastique. Leurs égéries incarnent de véritables héroïnes et ces jus nous content des récits toujours plus envoûtants. Alors, si vous êtes à la recherche de votre premier parfum de jeunes femmes, laissez-vous bercer par la tendresse de ce type d'essences. Laissez-vous guider par votre insouciance. Vous aurez ensuite largement le temps de prendre les choses au sérieux… Pour l'instant, faites plutôt de votre quotidien une douce utopie.</h5>
              <h3 className="ml-2 mr-2"> QUEL PARFUM POUR UNE JEUNE FEMME DE 20 ANS ?</h3>
              <img src="https://www.tendance-parfums.com/media/wysiwyg/CHOISIR-PARFUM/quel-parfum-pour-une-jeune-femme-de-20-ans.jpg" className="rounded float-left"/>
              <h5>À 20 ans, il n'est plus question de parler de jeunes filles mais plutôt de jeunes femmes. Les années lycée sont maintenant derrière vous et l'avenir professionnel se dessine peu à peu à l'horizon sans être encore réellement défini. À 20 ans, le futur est encore plein de promesses et d'innombrables transformations inondent votre quotidien. À cet âge-là, toutes les femmes ou presque ont envie de croquer la vie à pleines dents, d'embrasser le quotidien avec une joie de vivre insatiable et audacieuse. C'est donc à la fois ce mélange d'incertitudes et cette fougue incontrôlable que l'on devra ressentir dans son parfum.</h5>
              <h5>Les parfums pour enfants, c'est-à-dire ceux que l'on peut porter à partir de trois ans, visent surtout à satisfaire le plaisir des enfants. En effet, les petites filles aiment généralement reproduire les gestes de leurs parents. Par conséquent, elles se parfument surtout pour faire comme leur maman. Cela leur permet néanmoins de sentir bon et d'appréhender les premières odeurs. À cet âge, comme pour les bébés dans une moindre mesure, leur peau est plus fragile. Les parfums contiennent donc peu d'alcool. Ils sont souvent assez fruités, gourmands et très girly. En d'autres termes, ils sentent bon la petite fille. C'est à partir de l'adolescence que le parfum se modifie. C'est à cet instant que les jeunes filles choisissent leur premier vrai parfum. L'idée est toutefois de préserver leur insouciance et de ne pas encore les orienter vers une fragrance qui fasse trop adulte. Pour cela, l’objectif est de trouver un juste compromis entre les senteurs enfantines et celles d'une vraie femme. Nous vous recommandons de vous orienter vers des senteurs légères et aériennes, fraîches et acidulées, un brin gourmandes. En règle générale, les jeunes filles aiment les parfums qui les plongent dans un univers bucolique et poétique. </h5>
              <h3 className="ml-2 mr-2">20 ans, ou le moment de l'incertitude</h3>
              <h5>Lorsque l'on a 20 ans, il n'est pas rare de ressentir un sentiment assez paradoxal. D'un côté, nous sommes enfin adultes et nous nous sentons en pleine possession de nos moyens. Nous regorgeons d'une énergie débordante et l'avenir semble ainsi nous appartenir. Certains jours, nous nous sentons pousser des ailes. Pourtant, à d'autres moments, le futur parait plus incertain. Nous ne savons pas réellement de quoi sera fait le lendemain et, même si cela peut s'avérer excitant, il faut bien reconnaître que c'est aussi préoccupant et quelque peu anxiogène. 20 ans est donc un âge plein d'incertitudes et de changements. Cela se remarque aussi sur le plan olfactif. Il est presque impossible d'avoir trouvé son parfum idéal alors que l'on entre à peine dans la vingtaine. Pour trouver le jus qui sera fait pour vous, il vous faudra probablement en changer régulièrement. C'est à force de tester de nouvelles matières premières différentes que vous finirez par trouver celles qui seront vos favorites pour les années à venir. N'hésitez donc pas à vous laisser guider par les tendances et à tester les blockbusters du moment de la parfumerie. Après tout, si certains parfums ont particulièrement le vent en poupe, ce n'est sans doute pas sans raison…</h5>
              <h3 className="ml-2 mr-2">LES ESSENCES APPRÉCIÉES DES FEMMES DE 30 ANS</h3>
              <img src="https://www.tendance-parfums.com/media/wysiwyg/CHOISIR-PARFUM/les-essences-appreciees-des-femmes-de-30-ans.jpg" className="rounded float-left"/>
              <h5> À 30 ans, l’âge de l'insouciance est passé et les femmes commencent réellement à s'affirmer. Contrairement aux hommes qui ont à peine mûri, elles ont déjà acquis une certaine maturité et savent précisément ce qui leur faut. Les femmes trentenaires sont beaucoup plus sûres de leurs choix mais restent malgré tout en pleine construction. Elles sont particulièrement actives et sont sur tous les fronts à la fois. Elles doivent non seulement gérer leur évolution professionnelle mais commencent, pour la plupart d'entre elles, à fonder aussi une famille. Par conséquent, il leur faut des parfums capables de les accompagner dans ce rythme effréné.</h5>
              <h3 className="ml-2 mr-2">30 ans, le bel âge pour être une working girl</h3>
              <h5> La trentenaire d'aujourd'hui est bien différente de celle de l'époque de nos mamans ou encore de nos grands-mères. Elle place sa carrière au-dessus de toute chose mais ne veut pas pour autant en être moins séduisante. Les femmes de 30 ans sont intelligentes, coquettes, pleines de vie et ambitieuses. Certains diront même qu'elles le sont parfois un peu trop… Qu'à cela ne tienne, rien ne leur fait peur et rien ne semble pouvoir les ralentir. Pour pouvoir suivre ce rythme, les trentenaires ont besoin d'un parfum vivifiant et dynamisant, agissant comme une sorte de coup de fouet dans leur quotidien. Pour ce faire, les femmes choisissent souvent des jus très aériens, à base d'agrumes ou de saveurs aquatiques. Ces derniers dégagent une sensation de vitalité immédiate et les accompagnent ainsi jour après jour dans leurs innombrables défis. Les parfums revigorants de ce genre font également penser au souffle frais des déodorants. Ainsi, ils permettent de ressentir un certain contrôle de soi-même et de ses émotions, un indispensable pour les working girls de notre époque  </h5>
            <br/> <br/>
        <h4 className="ml-2 mr-2">QUEL PARFUM HOMME CHOISIR ?</h4> <br/>
        <img src="https://www.tendance-parfums.com/media/wysiwyg/quel-parfum-homme-choisir.jpg" className="rounded mx-auto d-block"/> <br/>
        <h5>Si le parfum a longtemps été associé à la femme, il est devenu aujourd’hui, une arme de séduction à part entière. Longtemps, les hommes n’utilisaient que de l’Eau de Cologne, des eaux souvent hespéridées et fraiches. Dans les années 60 apparaissent enfin, des eaux beaucoup plus masculines. Ce sont les années 70 qui révolutionneront le monde de la parfumerie masculine avec l’arrivée de grands parfums mythiques et masculins. Dans les années 80, les parfums pour hommes connaissent une véritable révolution et deviennent virils à souhait.</h5>
        <h5>À l’heure actuelle, il existe de très nombreux parfums masculins, que l’on choisit selon son âge, mais aussi selon son caractère, son style vestimentaire ou encore son style de vie. Mystérieux, séduisant, discret, viril… À chaque homme correspond un parfum. Si certains hommes choisissent également leur parfum selon leur signe astrologique, ils arrivent que ce soient les femmes qui choisissent le parfum de leur homme. Comment s’y retrouver entre ses gouts, ses besoins, les différentes familles olfactives et les marques ?</h5>
        <h3 className="ml-2 mr-2"> QUEL TYPE DE PARFUM MASCULIN CHOISIR SELON SON ÂGE ?</h3>
        <img src="https://www.tendance-parfums.com/media/wysiwyg/CHOISIR-PARFUM/quel-type-de-parfum-masculin-choisir-selon-son-age.jpg" className="rounded float-left"/>
        <h5>Selon l’âge, et selon que l’on soit ado, mature ou sénior, le parfum ne sera pas choisi de la même manière. Un homme évolue et affirme ses goûts tout au long de sa vie. Un parfum changera en fonction de son style de vie, son style vestimentaire, sa vie, sa femme.</h5>
        <h3 className="ml-2 mr-2">Parfum ado garçon</h3>
        <h5>Lorsqu’on est ado, il n’est pas évident de trouver un parfum qui nous corresponde. Non seulement les goûts ne sont pas entièrement déterminés, mais en plus ils changent souvent… La plupart des ados garçons optent pour un parfum frais et épicé. Néanmoins, certains aiment les odeurs qui s’imposent et qui correspondent déjà à un style bien affirmé.</h5>
        <h3 className="ml-2 mr-2">Parfum Homme 20 ans</h3>
        <h5>À partir de 20 ans, le style du jeune homme est plus affirmé. Le parfum sera différent si le jeune homme est branché, romantique, exubérant ou discret. À cet âge, beaucoup choisissent les Eaux de Cologne, ou alors des fragrances sportives, aquatiques et fraiches. De nombreuses marques proposent des versions sportives de leur fragrance star, qui s’accommodent parfaitement à la vie quotidienne lorsqu’on a 20 ans. </h5>
        <h3 className="ml-2 mr-2">Parfum Homme 30 ans</h3>
        <h5> Le trentenaire est généralement un homme dynamique et bien entendu, jeune ! Il est souvent au tout début de sa vie active, et sa personnalité est dorénavant affirmée. Entre fragrances aromatiques, boisées, épicées, sportives ou orientales, le choix est vaste. Selon la profession de l’homme de 30 ans, et ses passions, le parfum sera dynamique, discret ou imposant  </h5>
        <h3 className="ml-2 mr-2">Parfum Homme 40 ans</h3>
        <h5> À 40 ans, l’homme est au mieux de ses capacités physiques, personnelles et professionnelles. C’est l’âge où l’homme est accompli. Selon s’il a un caractère jeune, baroudeur, discret, qui aime s’imposer, qui aime séduire, qui veut absolument être remarqué, ou tout simplement chic, le parfum s’adaptera à sa personnalité affirmée. </h5>
        <h3 className="ml-2 mr-2">Parfum Homme 50 ans</h3>
        <h5>À 50 ans, l’homme a eu des enfants, des expériences professionnelles, une ou plusieurs femmes et il sait désormais ce qu’il veut et ce qu’il ne veut pas. Séduisant et charismatique, l’homme de 50 ans aura un parfum qui mettra en valeur son aura et sa personnalité, un parfum à la fois séduisant et oriental.  </h5>
        <h3 className="ml-2 mr-2">Parfum Homme 60 ans</h3>
        <h5> À 60 ans, les hommes sont généralement pères et souvent grands-pères. Ils sont encore dans la vie active et aiment que l’on reconnaisse leur expérience. Leur parfum sera à la fois frais et chic. Certains seront plus discrets que d’autres avec des parfums plutôt hespéridés. D’autres seront un peu plus virils, avec des parfums plutôt aromatiques. </h5>
        <h3 className="ml-2 mr-2">Parfum Homme 70 ans</h3>
        <h5> À 70 ans, l’homme d’aujourd’hui séduit encore et toujours. Généralement à la retraite, il aime faire ce qu’il veut. Son parfum est légèrement viril, boisé, mais avant tout imposant, c’est un homme que l’on remarque. L’homme de 70 ans connait parfaitement ses goûts et adaptera ses parfums à ses sorties… </h5>
        <h3 className="ml-2 mr-2">Parfum Homme 80 ans</h3>
        <h5> Le parfum d’un homme de 80 ans est le parfum d’un homme qui a vécu. Racé et rempli de séduction, son parfum pourra être une fragrance fougère-boisée ou fougère-orientale, remplie de caractère. Néanmoins certains hommes de 80 ans reviennent aux Eaux de Cologne, ultras fraiches et délicates.</h5>

            </div>

        );
};

export default ChoosePerfume;

